apiVersion: v1
kind: Service
metadata:
  name:  {{ include "app.nameWithEnv" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id:  {{ include "app.nameWithEnv" . }}
    app.kubernetes.io/name:  {{ include "app.nameWithEnv" . }}
    app.kubernetes.io/instance:  {{ include "app.nameWithEnv" . }}
    app.kubernetes.io/component: application
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name:  {{ include "app.nameWithEnv" . }}
    app.kubernetes.io/instance:  {{ include "app.nameWithEnv" . }}

